app_admin/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',dashboard,name="dashboard"),
    
]

app_auth/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('login',login_blog,name='login-blog'),
    path('register',register,name='register'),
    path('logout',logout_blog,name='logout'),
]

blog/urls.py
from django import views
from django.urls import path
from . import views

urlpatterns = [
    path("",views.home,name="home"),
    path("article/<int:id_article>/", views.detail, name="detail"),
    path("search/", views.search, name="search"),
]

my_blog/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import home,detail,search,sms

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('',home, name="home"),
    path('article/<int:id_article>',detail,name="detail"),
    path('article/recherche',search,name="search"),
    path('message-sms',sms,name="sms"),
    path('auth/',include("app_auth.urls")),
    path('my-admin/',include("app_admin.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_admin/models.py
from django.db import models

# Create your models here.

app_auth/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=120)
    
    def __str__(self):
        return self.name
    
### Article avec ces Attributs   
class Article(models.Model):
    title=models.CharField(max_length=50)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    desc=models.TextField()
    image=models.ImageField(blank=True,null=True)
    published=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        return self.title

app_auth/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="Nom utilisateur",widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(label="Mot de passe",widget=forms.PasswordInput(attrs={'class':'form-control'}))

class RegisterForm(forms.Form):
    username = forms.CharField(label="Nom utilisateur",widget=forms.TextInput(attrs={'class':'form-control'}))
    pwd = forms.CharField(label="Mot de passe",widget=forms.PasswordInput(attrs={'class':'form-control'}))
    pwd_confirm = forms.CharField(label="Mot de passe de confirmation",widget=forms.PasswordInput(attrs={'class':'form-control'}))
    
        

app_admin/views.py
from django.shortcuts import render

def dashboard(request):
    return render(request,'db.html')

app_auth/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import *

def login_blog(request):
    if request.method == "POST":            
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            pwd = form.cleaned_data['pwd']
            user = authenticate(username=username,password=pwd)
            if user is not None:
                login(request,user)
                return redirect('home')
            else:
                messages.error(request,"Authentification échouée")
                return render(request,'login.html',{'form':form})
        else:
            for field in form.errors:
              form[field].field.widget.attrs['class'] += ' is-invalid'
            return render(request,'login.html',{'form':form})
                
    else:
        form = LoginForm()    
        return render(request,'login.html',{'form':form})  
    
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            pwd = form.cleaned_data['pwd']
            user = User.objects.create_user(username = username,password = pwd)
            if user is not None:
                return redirect("login-blog")
            else:
                messages.error(request,'Création de compte échouée')
                return render(request,'register.html',{'form':form})
        else:
            return render(request,'register.html',{'form':form})      
        return render(request,'register.html',{})
    
    form = RegisterForm()
    return render(request,'register.html',{'form':form})

def logout_blog(request):
    logout(request)
    return redirect('login-blog')
    
          

blog/views.py
from unicodedata import category
from django import http
from django.shortcuts import render
from .models import Article, Category
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

def home(request):
    list_articles=Article.objects.filter(published=True).order_by('-created_at')
    paginator = Paginator(list_articles, 4) # Affiche 4 articles par page
    
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context= {"liste_articles":page_obj}
    return render(request,"index.html",context) 

### Détaille sur un Article
def detail(request,id_article):
    article=Article.objects.get(id=id_article, published=True)
    category=article.category
    article_en_relation=Article.objects.filter(category=category, published=True).exclude(id=id_article)[:5]
    return render(request,'detail.html',{"article":article,"aer":article_en_relation})
    
### Recherche sur un Article
def search(request):
    query=request.GET["article"]
    liste_article=Article.objects.filter(title__contains=query, published=True)
    return render(request,"search.html",{"liste_article":liste_article})

@login_required
def sms(request):
    message=request.GET['body']
    message_splited=message.split("-")
    title=message_splited[0]
    desc=message_splited[1]
    
    agri_category=Category.objects.get(id=2)
    article= Article(title=title,category=agri_category,desc=desc,image="http://default")
    article.save()
    print('data saved successfully')
    return http.HttpResponse("data saved successfully")

app_admin/templates/db.html
{% extends 'partials/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Tableau de bord</h2>
        </div>
    </div>
</div>

{% endblock %}

app_admin/templates/partials/_navadmin.html
<!--Navbar -->
<nav class="mb-1 navbar navbar-expand-lg navbar-dark default-color">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
      aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Dropdown
          </a>
          <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto nav-flex-icons">
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light">
            <i class="fab fa-google-plus-g"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-default"
            aria-labelledby="navbarDropdownMenuLink-333">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
  <!--/.Navbar -->

app_admin/templates/partials/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Tableau de bord {% endblock %}</title>

    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static  'css/bootstrap.min.css' %}">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="{% static  'css/mdb.min.css' %}">
    <!-- Your custom styles (optional) -->
    
    
</head>
<body>
    {% include '_navadmin.html'%}
    
    {% block content %}
    {% endblock %}

    <!-- jQuery -->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Your custom scripts (optional) -->
    <script type="text/javascript"></script>
    
</body>
</html>

app_auth/templates/login.html
 {% extends 'base.html' %}  

 {% block title %} Connexion {% endblock %}

 {% block content %}

 <div class="container d-flex aligns-items-center justify-content-center">
    <div class="col-md-6 mt-5 mb-5"> 
        
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger text-center"><strong>{{message}}</strong></div>
        {% endfor %}
        {%  endif %}
        
        <form action="" method="POST" novalidate> {% csrf_token %}
            <div class="card m-2 p-5">
                <div class="card-header text-center"><i class="fas fa-user"></i>Connexion </div>
                <div class="card-body">  
                    <label for="id_username">Nom utilisateur</label> 
                    {% if form.username.errors %} 
                    {% for error in form.username.errors %}
                    <div class="div-error-{{form.username.name}}"><small class="text-danger">{{error}}</small></div>
                    {% endfor %}
                    {% endif %}
                    {{form.username}}   

                    
                    <label for="id_pwd">Mot de passe</label>  
                    {% if form.pwd.errors %} 
                    {% for error in form.pwd.errors %}
                    <div class="div-error-{{form.pwd.name}}"><small class="text-danger">{{error}}</small></div>
                    {% endfor %}
                    {% endif %}           
                    {{form.pwd}}                
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary btn-block">Se connecter</button>
                    
                <p class="mt-2">Vous n'avez pas de compte ? <a href="{% url 'register' %}">Créer le compte</a></p>
                </div>
                
            </div>
        </form>          
    </div>
 </div>
 {% endblock %}

 {% block script %}
 <script>
    $(document).ready(function(){
        $('input').keyup(function(){
            let textSaisi = $(this).val();

            let attrName = $(this).attr('name');
            let validatorElement =".div-error-"+attrName;
            if(textSaisi == ""){
                if(!$(this).hasClass('is-invalid')){
                    $(this).addClass('is-invalid');

                    $(validatorElement).show();
                }
            }else {
                $(this).removeClass('is-invalid')

                $(validatorElement).hide();
            }
        })

    })
 </script>
 {% endblock %}

 

 

app_auth/templates/register.html
{% extends 'base.html' %}  

{% block title %} Création de compte au stock {% endblock %}

{% block content %}

<div class="container d-flex aligns-items-center justify-content-center">
   <div class="col-md-6 mt-5 mb-5"> 
       {% if messages %}
       {% for message in messages %}
       <div class="alert alert-danger text-center"><strong>{{message}}</strong></div>
       {% endfor %}
       {%  endif %}
       
       <form action="" method="POST" novalidate> {% csrf_token %}
           <div class="card">
               <div class="card-header text-center"><i class="fas fa-user-lock"></i>Création de compte </div>
               <div class="card-body">  
                {{form}}     
               </div>
               <div class="card-footer">
                   <button class="btn btn-primary btn-block">Créer le compte</button>
               </div>
           </div>
       </form>          
   </div>
</div>
{% endblock %}

{% block script %}

{% endblock %}

blog/templates/_footer.html
<!-- Footer -->
<footer class="page-footer font-small stylish-color-dark pt-4">

    <!-- Footer Links -->
    <div class="container text-center text-md-left">
  
      <!-- Grid row -->
      <div class="row">
  
        <!-- Grid column -->
        <div class="col-md-4 mx-auto">
  
          <!-- Content -->
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Footer Content</h5>
          <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
            consectetur
            adipisicing elit.</p>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-2 mx-auto">
  
          <!-- Links -->
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-2 mx-auto">
  
          <!-- Links -->
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-2 mx-auto">
  
          <!-- Links -->
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="#!">Link 1</a>
            </li>
            <li>
              <a href="#!">Link 2</a>
            </li>
            <li>
              <a href="#!">Link 3</a>
            </li>
            <li>
              <a href="#!">Link 4</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Grid row -->
  
    </div>
    <!-- Footer Links -->
  
    <hr>
  
    <!-- Call to action -->
    <ul class="list-unstyled list-inline text-center py-2">
      <li class="list-inline-item">
        <h5 class="mb-1">Register for free</h5>
      </li>
      <li class="list-inline-item">
        <a href="#!" class="btn btn-danger btn-rounded">Sign up!</a>
      </li>
    </ul>
    <!-- Call to action -->
  
    <hr>
  
    <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-gplus mx-1">
          <i class="fab fa-google-plus-g"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-li mx-1">
          <i class="fab fa-linkedin-in"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-dribbble mx-1">
          <i class="fab fa-dribbble"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="/"> MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->

blog/templates/_nav.html
 <!--Navbar-->
 <nav class="navbar navbar-expand-lg navbar-ligth">

    <!-- Navbar brand -->
    <a class="navbar-brand" href="#">Mes stocks</a>
  
    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
      aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">
  
      <!-- Links -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Admin
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
  
        <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Mon compte</a>
          <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
  
      </ul>
      <!-- Links -->
      {% if user.is_authenticated %}
      <a href="{% url 'logout' %}" class="btn btn-info">Déconnexion</a>
      {% else %}
      <a href="{% url 'login-blog' %}" class="btn btn-info">Connexion</a>
      {% endif %}
      <form class="form-inline" action="{% url 'search' %}">
        <div class="md-form my-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Recherche" aria-label="Search" name="article">
        </div>
      </form>
    </div>
    <!-- Collapsible content -->
  
  </nav>
  <!--/.Navbar-->

blog/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %} My blog {% endblock %}</title>

    <!-- MDB icon -->
    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static  'css/bootstrap.min.css' %}">
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="{% static  'css/mdb.min.css' %}">
    <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    {% include '_nav.html' %}

    {% block content %}
    {% endblock  %}

    {% include '_footer.html' %}


    <!-- jQuery -->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Your custom scripts (optional) -->
    <script type="text/javascript"></script>

    {% block script %}
    {% endblock %}
</body>
</html>

blog/templates/brouillon.html
{% include '_nav.html' %}

<a href="https://via.placeholder.com/400"></a>
{{article.image.url}}

blog/templates/detail.html
{% extends 'base.html' %}

{% load static %}
    
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1 class="text-center my-4">Détail de l'article</h1>
            <img src="{{article.image.url}}" alt="Image de {{article.title}}" class="img-fluid rounded shadow-sm mb-4">
            <h2 class="mt-3">{{article.title}}</h2>
            <p class="lead">{{article.desc}}</p>
            <a href="{% url 'home' %}" class="btn btn-secondary my-3">Retour au stock</a>
        </div>
        <div class="col-md-4">
            <h3 class="my-4">Articles similaires</h3>
            {% for art in aer %} 
            <a href="{% url 'detail' art.id %}" class="text-decoration-none text-dark">
                <div class="card mb-3 shadow-sm">
                    <div class="row g-0">
                        <div class="col-md-5">
                            {% if art.image != "http://default" %} 
                                <img src="{{art.image.url}}" class="img-fluid rounded-start" alt="Image de {{art.title}}" style="height: 100%; object-fit: cover;">
                            {% else %}
                                <img src="{% static 'img/logo.png' %}" class="img-fluid rounded-start" alt="Image par défaut" style="height: 100%; object-fit: cover;">
                            {% endif %}
                        </div>
                        <div class="col-md-7">
                            <div class="card-body">
                                <h5 class="card-title" style="font-size: 1rem;">{{art.title}}</h5>
                                <p class="card-text" style="font-size: 0.85rem;">
                                    <small class="text-muted">{{art.desc|truncatewords:7}}</small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            {% endfor%}
        </div>                
    </div>
</div>
{%endblock%}

blog/templates/index.html
{% extends 'base.html' %} 


{% load static %}

{% block content%}
<h1 class="text-center mt-3">Bienvenue sur notre stock</h1>
<div class="container">
      <div class="row">
        {% for article in liste_articles %}
        <div class="col-12 col-md-6 col-lg-3 col-xl-3">
            <div class="card mb-2 p-2"> 
              <!-- Card image -->
              {% if article.image == "http://default" %}
              <a href="{% url 'detail' article.id %}">
                <img class="card-img-top" src="{% static 'img/logo.png' %}" alt="Card image cap" style="height:200px">
              </a>
              {% else %}
              <a href="{% url 'detail' article.id %}">
                <img class="card-img-top" src="{{article.image.url}}" alt="Card image cap" style="height:200px">
              </a>
              {% endif %}
        
              <!-- Card content -->
              <div class="card-body" style="height:220px;">
        
                  <!-- Title -->
                  <h4 class="card-title"><a href="{% url 'detail' article.id %}">{{article.title}}</a></h4>
                  <!-- Text -->
                  <p class="card-text">{{article.desc|truncatewords_html:8}}</p>
                  <p class="card-text">Publié il y a {{article.created_at| timesince}}</p>
                  <!-- Button -->
                 <a href="{% url 'detail' article.id %}" class="btn btn-primary">Lire la suite </a>		  
              </div>		          
            </div>
        </div>
        {% endfor %}		           	 
      </div>
  <!--end row-->

  <nav class="my-4">
    <ul class="pagination justify-content-center">
      {% if liste_articles.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ liste_articles.previous_page_number }}">Précédent</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Précédent</a>
        </li>
      {% endif %}

      {% for num in liste_articles.paginator.page_range %}
        {% if liste_articles.number == num %}
          <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
      {% endfor %}

      {% if liste_articles.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ liste_articles.next_page_number }}">Suivant</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Suivant</a></li>
      {% endif %}
    </ul>
  </nav>
</div>
{%endblock%}

blog/templates/search.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container">
    <h2> Liste de recheche</h2>
    <div class="row">
        {% for article in liste_article %}
        <div class="col-12 col-md-6 col-lg-3 col-xl-3">
            <div class="card mb-2 p-2"> 
              <!-- Card image -->
              {% if article.image == "http://default" %}
              <a href="{% url 'detail' article.id %}">
                <img class="card-img-top" src="{% static 'img/logo.png' %}" alt="Card image cap" style="height:200px">
              </a>
              {% else %}
              <a href="{% url 'detail' article.id %}">
                <img class="card-img-top" src="{{article.image.url}}" alt="Card image cap" style="height:200px">
              </a>
              {% endif %}
        
              <!-- Card content -->
              <div class="card-body" style="height:220px;">
        
                  <!-- Title -->
                  <h4 class="card-title"><a href="{% url 'detail' article.id %}">{{article.title}}</a></h4>
                  <!-- Text -->
                  <p class="card-text">{{article.desc|truncatewords_html:8}}</p>
                  <p class="card-text">Publié il y a {{article.created_at| timesince}}</p>
                  <!-- Button -->
                 <a href="{% url 'detail' article.id %}" class="btn btn-primary">Lire la suite </a>		  
              </div>		          
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}